### ISSUE TITLE
Regex Add_articles.php website input

### ISSUE THREAD

**Issue by codymalick** [matthewrsj/jedi-temple#49]
Check URL input for valid url. The links are broken unless the url field contains a valid url.

**Comment by codymalick** [comment]
This isn't an issue is we authenticate the user input user regex on add_articles.php

**Comment by matthewrsj** [comment]
what even is this?

**Comment by matthewrsj** [comment]
I assume you know, and I will assign this to you.

**Comment by matthewrsj** [comment]
Ok, so @codymalick is right, the links actually work if the url the user inputs is a valid link.

**Comment by matthewrsj** [comment]
Instead, let's do this: http://stackoverflow.com/a/207627
